name: github_pages
description: Publish your web application to a gh-pages branch on GitHub.
version: 1.0.0
homepage: https://github.com/javoeria/gh-pages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  git: ^2.0.0
  path: ^1.8.0
  process_run: ^0.12.1

dev_dependencies:
  pedantic: ^1.11.0
