name: gh_pages
description: Publish to a gh-pages branch on GitHub (or any other branch on any other remote)
version: 0.0.1
homepage: https://github.com/javoeria/gh-pages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  git: ^2.0.0
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
