name: github_pages
description: Publish to a gh-pages branch on GitHub (or any other branch on any other remote)
version: 2.0.0-dev
homepage: https://github.com/javoeria/gh-pages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.4.0
  git: ^2.2.0
  glob: ^2.1.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.1
